# Generated by Django 5.0.7 on 2024-07-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='file',
        ),
        migrations.AddField(
            model_name='comment',
            name='file',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
